<?php

namespace AppBundle\Repository;

/**
 * AdmiTipoComidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiTipoComidaRepository extends \Doctrine\ORM\EntityRepository
{
}
