<?php

namespace AppBundle\Repository;

/**
 * AdmiProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiProvinciaRepository extends \Doctrine\ORM\EntityRepository
{
}
