<?php

namespace AppBundle\Repository;

/**
 * AdmiTipoRolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiTipoRolRepository extends \Doctrine\ORM\EntityRepository
{
}
