<?php

namespace AppBundle\Repository;

/**
 * AdmiAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
