<?php

namespace AppBundle\Repository;

/**
 * AdmiRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
