<?php

namespace AppBundle\Repository;

/**
 * AdmiParroquiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiParroquiaRepository extends \Doctrine\ORM\EntityRepository
{
}
