<?php

namespace AppBundle\Repository;

/**
 * AdmiModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiModuloRepository extends \Doctrine\ORM\EntityRepository
{
}
