<?php

namespace AppBundle\Repository;

/**
 * AdmiParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiParametroRepository extends \Doctrine\ORM\EntityRepository
{
}
