<?php

namespace AppBundle\Repository;

/**
 * AdmiSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiSectorRepository extends \Doctrine\ORM\EntityRepository
{
}
