<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * Método encargado de retornar todos los paises según los parámetros enviados.
     * 
     * @author Kevin Baque
     * @version 1.0 16-07-2019
     * 
     * @return array  $arrayCiudad
     * 
     */
    public function getCiudad($arrayParametros)
    {
        $strEstado       = $arrayParametros['estado'] ? $arrayParametros['estado']:'Activo';
        $strProvincia    = $arrayParametros['provincia'] ? $arrayParametros['provincia']:'';
        $arrayCiudad     = array();
        $objRsmBuilder   = new ResultSetMappingBuilder($this->_em);
        $objQuery        = $this->_em->createNativeQuery(null, $objRsmBuilder);
        $strMensajeError = '';
        $strSelect       = '';
        $strFrom         = '';
        $strWhere        = '';
        try
        {
            $strSelect = "SELECT ciudad.CIUDAD_NOMBRE,ciudad.PAIS_CODIGO,ciudad.ESTADO ";
            $strFrom   = "FROM ADMI_CIUDAD ciudad ";
            $strWhere  = "WHERE lower(ciudad.ESTADO) = lower(:ESTADO) ";
            $objQuery->setParameter("ESTADO", $strEstado);
            if(!empty($strProvincia))
            {
                $strWhere  .= " AND lower(ciudad.CIUDAD_DISTRITO) = lower(:CIUDAD_DISTRITO) ";
                $objQuery->setParameter("CIUDAD_DISTRITO", $strProvincia);
            }
            $objRsmBuilder->addScalarResult('CIUDAD_NOMBRE', 'CIUDAD_NOMBRE', 'string');
            $objRsmBuilder->addScalarResult('PAIS_CODIGO', 'PAIS_CODIGO', 'string');
            $objRsmBuilder->addScalarResult('ESTADO', 'ESTADO', 'string');

            $strSql  = $strSelect.$strFrom.$strWhere;
            $objQuery->setSQL($strSql);
            $arrayCiudad['ciudad'] = $objQuery->getResult();
        }
        catch(\Exception $e)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCiudad['error'] = $strMensajeError;
        return $arrayCiudad;
    }
}
