<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * Metodo encargado de retornar todos los paises según los parametros enviados.
     * 
     * @author Kevin Baque
     * @version 1.0 16-07-2019
     * 
     * @return array  $arrayCiudad
     * 
     */
    public function getCiudad($arrayParametros)
    {
        $strEstado     = $arrayParametros['estado'] ? $arrayParametros['estado']:'';
        $arrayCiudad   = array();
        $objRsmBuilder = new ResultSetMappingBuilder($this->_em);
        $objQuery      = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            $strSelect = "SELECT ciudad.CiudadNombre,ciudad.PaisCodigo,ciudad.ESTADO ";
            $strFrom   = "FROM Ciudad ciudad ";
            $strWhere  = "WHERE ciudad.ESTADO=:ESTADO";
            $objQuery->setParameter("ESTADO", $strEstado);
            $objRsmBuilder->addScalarResult('CiudadNombre', 'CiudadNombre', 'string');
            $objRsmBuilder->addScalarResult('PaisCodigo', 'PaisCodigo', 'string');
            $objRsmBuilder->addScalarResult('ESTADO', 'ESTADO', 'string');

            $strSql  = $strSelect.$strFrom.$strWhere;
            $objQuery->setSQL($strSql);
            $arrayCiudad['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $e)
        {
            error_log('getCiudad -> '.$e->getMessage());
            throw($e);
        }
        return $arrayCiudad;
    }
}
