<?php

namespace AppBundle\Repository;

/**
 * InfoRedesSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRedesSocialesRepository extends \Doctrine\ORM\EntityRepository
{
}
