<?php

namespace AppBundle\Repository;

/**
 * InfoModuloAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoModuloAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
