<?php

namespace AppBundle\Repository;

/**
 * InfoVistaPublicidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoVistaPublicidadRepository extends \Doctrine\ORM\EntityRepository
{
}
