<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * Metodo encargado de retornar todos los paises según los parametros enviados.
     * 
     * @author Kevin Baque
     * @version 1.0 16-07-2019
     * 
     * @return array  $arrayPais
     * 
     */    
    public function getPais($arrayParametros)
    {
        $strEstado     = $arrayParametros['estado'] ? $arrayParametros['estado']:'';
        $arrayPais     = array();
        $objRsmBuilder = new ResultSetMappingBuilder($this->_em);
        $objQuery      = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            $strSelect = "SELECT pais.PaisNombre,pais.PaisCodigo,pais.ESTADO ";
            $strFrom   = "FROM Pais pais ";
            $strWhere  = "WHERE pais.ESTADO=:ESTADO";
            $objQuery->setParameter("ESTADO", $strEstado);
            $objRsmBuilder->addScalarResult('PaisNombre', 'PaisNombre', 'string');
            $objRsmBuilder->addScalarResult('PaisCodigo', 'PaisCodigo', 'string');
            $objRsmBuilder->addScalarResult('ESTADO', 'ESTADO', 'string');

            $strSql  = $strSelect.$strFrom.$strWhere;
            $objQuery->setSQL($strSql);
            $arrayPais['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $e)
        {
            error_log('getPais -> '.$e->getMessage());
            throw($e);
        }
        return $arrayPais;
    }
}
