Insert into ADMI_CIUDAD values ('2','1','GIRÓN','ACTIVO');
Insert into ADMI_CIUDAD values ('5','1','PAUTE','ACTIVO');
Insert into ADMI_CIUDAD values ('6','1','PUCARÁ','ACTIVO');
Insert into ADMI_CIUDAD values ('7','1','SAN FERNANDO','ACTIVO');
Insert into ADMI_CIUDAD values ('8','1','SANTA ISABEL','ACTIVO');
Insert into ADMI_CIUDAD values ('9','1','SIGSIG','ACTIVO');
Insert into ADMI_CIUDAD values ('10','1','OÑA','ACTIVO');
Insert into ADMI_CIUDAD values ('11','1','CHORDELEG','ACTIVO');
Insert into ADMI_CIUDAD values ('12','1','EL PAN','ACTIVO');
Insert into ADMI_CIUDAD values ('13','1','SEVILLA DE ORO','ACTIVO');
Insert into ADMI_CIUDAD values ('14','1','GUACHAPALA','ACTIVO');
Insert into ADMI_CIUDAD values ('15','1','CAMILO PONCE ENRÍQUEZ','ACTIVO');
Insert into ADMI_CIUDAD values ('16','2','GUARANDA','ACTIVO');
Insert into ADMI_CIUDAD values ('17','2','CHILLANES','ACTIVO');
Insert into ADMI_CIUDAD values ('18','2','CHIMBO','ACTIVO');
Insert into ADMI_CIUDAD values ('20','2','SAN MIGUEL','ACTIVO');
Insert into ADMI_CIUDAD values ('21','2','CALUMA','ACTIVO');
Insert into ADMI_CIUDAD values ('22','2','LAS NAVES','ACTIVO');
Insert into ADMI_CIUDAD values ('23','3','AZOGUES','ACTIVO');
Insert into ADMI_CIUDAD values ('24','3','BIBLIÁN','ACTIVO');
Insert into ADMI_CIUDAD values ('25','3','CAÑAR','ACTIVO');
Insert into ADMI_CIUDAD values ('26','3','LA TRONCAL','ACTIVO');
Insert into ADMI_CIUDAD values ('27','3','EL TAMBO','ACTIVO');
Insert into ADMI_CIUDAD values ('28','3','DÉELEG','ACTIVO');
Insert into ADMI_CIUDAD values ('29','3','SUSCAL','ACTIVO');
Insert into ADMI_CIUDAD values ('30','4','TULCAN','ACTIVO');
Insert into ADMI_CIUDAD values ('31','4','BOLÍVAR','ACTIVO');
Insert into ADMI_CIUDAD values ('32','4','ESPEJO','ACTIVO');
Insert into ADMI_CIUDAD values ('33','4','MIRA','ACTIVO');
Insert into ADMI_CIUDAD values ('34','4','MONTÚFAR','ACTIVO');
Insert into ADMI_CIUDAD values ('35','4','SAN PEDRO DE HUACA','ACTIVO');
Insert into ADMI_CIUDAD values ('36','5','LATACUNGA','ACTIVO');
Insert into ADMI_CIUDAD values ('37','5','LA MANÁ','ACTIVO');
Insert into ADMI_CIUDAD values ('38','5','PANGUA','ACTIVO');
Insert into ADMI_CIUDAD values ('39','5','PUJILÍ','ACTIVO');
Insert into ADMI_CIUDAD values ('40','5','SALCEDO','ACTIVO');
Insert into ADMI_CIUDAD values ('41','5','SAQUISILÍ','ACTIVO');
Insert into ADMI_CIUDAD values ('42','5','SIGCHOS','ACTIVO');
Insert into ADMI_CIUDAD values ('43','6','RIOBAMBA','ACTIVO');
Insert into ADMI_CIUDAD values ('44','6','ALAUSI','ACTIVO');
Insert into ADMI_CIUDAD values ('45','6','COLTA','ACTIVO');
Insert into ADMI_CIUDAD values ('46','6','CHAMBO','ACTIVO');
Insert into ADMI_CIUDAD values ('47','6','CHUNCHI','ACTIVO');
Insert into ADMI_CIUDAD values ('48','6','GUAMOTE','ACTIVO');
Insert into ADMI_CIUDAD values ('49','6','GUANO','ACTIVO');
Insert into ADMI_CIUDAD values ('50','6','PALLATANGA','ACTIVO');
Insert into ADMI_CIUDAD values ('51','6','PENIPE','ACTIVO');
Insert into ADMI_CIUDAD values ('52','6','CUMANDÁ','ACTIVO');
Insert into ADMI_CIUDAD values ('53','7','MACHALA','ACTIVO');
Insert into ADMI_CIUDAD values ('54','7','ARENILLAS','ACTIVO');
Insert into ADMI_CIUDAD values ('55','7','ATAHUALPA','ACTIVO');
Insert into ADMI_CIUDAD values ('56','7','BALSAS','ACTIVO');
Insert into ADMI_CIUDAD values ('57','7','CHILLA','ACTIVO');
Insert into ADMI_CIUDAD values ('58','7','EL GUABO','ACTIVO');
Insert into ADMI_CIUDAD values ('59','7','HUAQUILLAS','ACTIVO');
Insert into ADMI_CIUDAD values ('60','7','MARCABELÍ','ACTIVO');
Insert into ADMI_CIUDAD values ('61','7','PASAJE','ACTIVO');
Insert into ADMI_CIUDAD values ('62','7','PIÑAS','ACTIVO');
Insert into ADMI_CIUDAD values ('63','7','PORTOVELO','ACTIVO');
Insert into ADMI_CIUDAD values ('64','7','SANTA ROSA','ACTIVO');
Insert into ADMI_CIUDAD values ('65','7','ZARUMA','ACTIVO');
Insert into ADMI_CIUDAD values ('67','8','ESMERALDAS','ACTIVO');
Insert into ADMI_CIUDAD values ('69','8','MUISNE','ACTIVO');
Insert into ADMI_CIUDAD values ('70','8','QUININDÉ','ACTIVO');
Insert into ADMI_CIUDAD values ('71','8','SAN LORENZO','ACTIVO');
Insert into ADMI_CIUDAD values ('72','8','ATACAMES','ACTIVO');
Insert into ADMI_CIUDAD values ('74','23','LA CONCORDIA','ACTIVO');
Insert into ADMI_CIUDAD values ('75','9','GUAYAQUIL','ACTIVO');
Insert into ADMI_CIUDAD values ('76','9','ALFREDO BAQUERIZO MORENO (JUJÁN)','ACTIVO');
Insert into ADMI_CIUDAD values ('78','9','BALZAR','ACTIVO');
Insert into ADMI_CIUDAD values ('79','9','COLIMES','ACTIVO');
Insert into ADMI_CIUDAD values ('80','9','DAULE','ACTIVO');
Insert into ADMI_CIUDAD values ('81','9','DURAN','ACTIVO');
Insert into ADMI_CIUDAD values ('82','9','EL EMPALME','ACTIVO');
Insert into ADMI_CIUDAD values ('83','9','EL TRIUNFO','ACTIVO');
Insert into ADMI_CIUDAD values ('84','9','MILAGRO','ACTIVO');
Insert into ADMI_CIUDAD values ('86','9','NARANJITO','ACTIVO');
Insert into ADMI_CIUDAD values ('87','9','PALESTINA','ACTIVO');
Insert into ADMI_CIUDAD values ('88','9','PEDRO CARBO','ACTIVO');
Insert into ADMI_CIUDAD values ('89','9','SAMBORONDÓN','ACTIVO');
Insert into ADMI_CIUDAD values ('90','9','SANTA LUCÍA','ACTIVO');
Insert into ADMI_CIUDAD values ('91','9','SALITRE (URBINA JADO)','ACTIVO');
Insert into ADMI_CIUDAD values ('92','9','SAN JACINTO DE YAGUACHI','ACTIVO');
Insert into ADMI_CIUDAD values ('93','9','PLAYAS','ACTIVO');
Insert into ADMI_CIUDAD values ('94','9','SIMON BOLIVAR','ACTIVO');
Insert into ADMI_CIUDAD values ('95','9','CORONEL MARCELINO MARIDUEÑA','ACTIVO');
Insert into ADMI_CIUDAD values ('96','9','LOMAS DE SARGENTILLO','ACTIVO');
Insert into ADMI_CIUDAD values ('97','9','NOBOL','ACTIVO');
Insert into ADMI_CIUDAD values ('98','9','GENERAL ANTONIO ELIZALDE (BUCAY)','ACTIVO');
Insert into ADMI_CIUDAD values ('99','9','ISIDRO AYORA','ACTIVO');
Insert into ADMI_CIUDAD values ('100','10','IBARRA','ACTIVO');
Insert into ADMI_CIUDAD values ('101','10','ANTONIO ANTE','ACTIVO');
Insert into ADMI_CIUDAD values ('102','10','COTACACHI','ACTIVO');
Insert into ADMI_CIUDAD values ('103','10','OTAVALO','ACTIVO');
Insert into ADMI_CIUDAD values ('104','10','PIMAMPIRO','ACTIVO');
Insert into ADMI_CIUDAD values ('105','10','SAN MIGUEL DE URCUQUÍ','ACTIVO');
Insert into ADMI_CIUDAD values ('106','11','LOJA','ACTIVO');
Insert into ADMI_CIUDAD values ('107','11','CALVAS','ACTIVO');
Insert into ADMI_CIUDAD values ('108','11','CATAMAYO','ACTIVO');
Insert into ADMI_CIUDAD values ('110','11','CHAGUARPAMBA','ACTIVO');
Insert into ADMI_CIUDAD values ('111','11','ESPÍNDOLA','ACTIVO');
Insert into ADMI_CIUDAD values ('112','11','GONZANAMÁ','ACTIVO');
Insert into ADMI_CIUDAD values ('113','11','MACARÁ','ACTIVO');
Insert into ADMI_CIUDAD values ('114','11','PALTAS','ACTIVO');
Insert into ADMI_CIUDAD values ('116','11','SARAGURO','ACTIVO');
Insert into ADMI_CIUDAD values ('117','11','SOZORANGA','ACTIVO');
Insert into ADMI_CIUDAD values ('118','11','ZAPOTILLO','ACTIVO');
Insert into ADMI_CIUDAD values ('119','11','PINDAL','ACTIVO');
Insert into ADMI_CIUDAD values ('120','11','QUILANGA','ACTIVO');
Insert into ADMI_CIUDAD values ('121','11','OLMEDO','ACTIVO');
Insert into ADMI_CIUDAD values ('122','12','BABAHOYO','ACTIVO');
Insert into ADMI_CIUDAD values ('3','1','GUALACEO','ACTIVO');
Insert into ADMI_CIUDAD values ('4','1','NABÓN','ACTIVO');
Insert into ADMI_CIUDAD values ('123','12','BABA','ACTIVO');
Insert into ADMI_CIUDAD values ('124','12','MONTALVO','ACTIVO');
Insert into ADMI_CIUDAD values ('125','12','PUEBLOVIEJO','ACTIVO');
Insert into ADMI_CIUDAD values ('126','12','QUEVEDO','ACTIVO');
Insert into ADMI_CIUDAD values ('127','12','URDANETA','ACTIVO');
Insert into ADMI_CIUDAD values ('128','12','VENTANAS','ACTIVO');
Insert into ADMI_CIUDAD values ('129','12','VINCES','ACTIVO');
Insert into ADMI_CIUDAD values ('131','12','BUENA FÉ','ACTIVO');
Insert into ADMI_CIUDAD values ('132','12','VALENCIA','ACTIVO');
Insert into ADMI_CIUDAD values ('133','12','MOCACHE','ACTIVO');
Insert into ADMI_CIUDAD values ('134','12','QUINSALOMA','ACTIVO');
Insert into ADMI_CIUDAD values ('135','13','PORTOVIEJO','ACTIVO');
Insert into ADMI_CIUDAD values ('136','13','BOLÍVAR','ACTIVO');
Insert into ADMI_CIUDAD values ('137','13','CHONE','ACTIVO');
Insert into ADMI_CIUDAD values ('138','13','EL CARMEN','ACTIVO');
Insert into ADMI_CIUDAD values ('139','13','FLAVIO ALFARO ','ACTIVO');
Insert into ADMI_CIUDAD values ('140','13','JIPIJAPA','ACTIVO');
Insert into ADMI_CIUDAD values ('141','13','JUNÍN','ACTIVO');
Insert into ADMI_CIUDAD values ('142','13','MANTA','ACTIVO');
Insert into ADMI_CIUDAD values ('143','13','MONTECRISTI','ACTIVO');
Insert into ADMI_CIUDAD values ('144','13','PAJÁN','ACTIVO');
Insert into ADMI_CIUDAD values ('145','13','PICHINCHA','ACTIVO');
Insert into ADMI_CIUDAD values ('146','13','ROCAFUERTE','ACTIVO');
Insert into ADMI_CIUDAD values ('147','13','SANTA ANA','ACTIVO');
Insert into ADMI_CIUDAD values ('148','13','SUCRE','ACTIVO');
Insert into ADMI_CIUDAD values ('149','13','TOSAGUA','ACTIVO');
Insert into ADMI_CIUDAD values ('150','13','24 DE MAYO','ACTIVO');
Insert into ADMI_CIUDAD values ('151','13','PEDERNALES','ACTIVO');
Insert into ADMI_CIUDAD values ('152','13','OLMEDO','ACTIVO');
Insert into ADMI_CIUDAD values ('153','13','PUERTO LÓPEZ','ACTIVO');
Insert into ADMI_CIUDAD values ('154','13','JAMA','ACTIVO');
Insert into ADMI_CIUDAD values ('155','13','JARAMIJÓ','ACTIVO');
Insert into ADMI_CIUDAD values ('156','13','SAN VICENTE','ACTIVO');
Insert into ADMI_CIUDAD values ('157','14','MORONA','ACTIVO');
Insert into ADMI_CIUDAD values ('158','14','GUALAQUIZA','ACTIVO');
Insert into ADMI_CIUDAD values ('159','14','LIMÓN INDANZA ','ACTIVO');
Insert into ADMI_CIUDAD values ('160','14','PALORA','ACTIVO');
Insert into ADMI_CIUDAD values ('161','14','SANTIAGO','ACTIVO');
Insert into ADMI_CIUDAD values ('162','14','SUCÚA','ACTIVO');
Insert into ADMI_CIUDAD values ('163','14','HUAMBOYA','ACTIVO');
Insert into ADMI_CIUDAD values ('164','14','SAN JUAN BOSCO','ACTIVO');
Insert into ADMI_CIUDAD values ('165','14','TAISHA','ACTIVO');
Insert into ADMI_CIUDAD values ('166','14','LOGROÑO','ACTIVO');
Insert into ADMI_CIUDAD values ('167','14','PABLO SEXTO','ACTIVO');
Insert into ADMI_CIUDAD values ('168','14','TIWINTZA','ACTIVO');
Insert into ADMI_CIUDAD values ('169','15','TENA','ACTIVO');
Insert into ADMI_CIUDAD values ('170','15','ARCHIDONA','ACTIVO');
Insert into ADMI_CIUDAD values ('171','15','EL CHACO','ACTIVO');
Insert into ADMI_CIUDAD values ('172','15','QUIJOS','ACTIVO');
Insert into ADMI_CIUDAD values ('173','15','CARLOS JULIO AROSEMENA TOLA','ACTIVO');
Insert into ADMI_CIUDAD values ('174','16','PASTAZA','ACTIVO');
Insert into ADMI_CIUDAD values ('175','16','MERA','ACTIVO');
Insert into ADMI_CIUDAD values ('176','16','SANTA CLARA','ACTIVO');
Insert into ADMI_CIUDAD values ('177','16','ARAJUNO','ACTIVO');
Insert into ADMI_CIUDAD values ('178','17','QUITO','ACTIVO');
Insert into ADMI_CIUDAD values ('179','17','CAYAMBE','ACTIVO');
Insert into ADMI_CIUDAD values ('180','17','MEJIA','ACTIVO');
Insert into ADMI_CIUDAD values ('181','17','PEDRO MONCAYO','ACTIVO');
Insert into ADMI_CIUDAD values ('182','17','RUMIÑAHUI','ACTIVO');
Insert into ADMI_CIUDAD values ('183','17','SAN MIGUEL DE LOS BANCOS','ACTIVO');
Insert into ADMI_CIUDAD values ('184','17','PEDRO VICENTE MALDONADO','ACTIVO');
Insert into ADMI_CIUDAD values ('185','17','PUERTO QUITO','ACTIVO');
Insert into ADMI_CIUDAD values ('186','18','AMBATO','ACTIVO');
Insert into ADMI_CIUDAD values ('187','18','BAÑOS DE AGUA SANTA','ACTIVO');
Insert into ADMI_CIUDAD values ('188','18','CEVALLOS','ACTIVO');
Insert into ADMI_CIUDAD values ('189','18','MOCHA','ACTIVO');
Insert into ADMI_CIUDAD values ('190','18','PATATE','ACTIVO');
Insert into ADMI_CIUDAD values ('191','18','QUERO','ACTIVO');
Insert into ADMI_CIUDAD values ('192','18','SAN PEDRO DE PELILEO','ACTIVO');
Insert into ADMI_CIUDAD values ('193','18','SANTIAGO DE PÍLLARO','ACTIVO');
Insert into ADMI_CIUDAD values ('194','18','TISALEO','ACTIVO');
Insert into ADMI_CIUDAD values ('195','19','ZAMORA','ACTIVO');
Insert into ADMI_CIUDAD values ('196','19','CHINCHIPE','ACTIVO');
Insert into ADMI_CIUDAD values ('197','19','NANGARITZA','ACTIVO');
Insert into ADMI_CIUDAD values ('198','19','YACUAMBÍ','ACTIVO');
Insert into ADMI_CIUDAD values ('199','19','YANTZAZA','ACTIVO');
Insert into ADMI_CIUDAD values ('200','19','EL PANGUI','ACTIVO');
Insert into ADMI_CIUDAD values ('201','19','CENTINELA DEL CÓNDOR','ACTIVO');
Insert into ADMI_CIUDAD values ('202','19','PALANDA','ACTIVO');
Insert into ADMI_CIUDAD values ('203','19','PAQUISHA','ACTIVO');
Insert into ADMI_CIUDAD values ('204','20','SAN CRISTOBAL','ACTIVO');
Insert into ADMI_CIUDAD values ('205','20','ISABELA','ACTIVO');
Insert into ADMI_CIUDAD values ('206','20','SANTA CRUZ','ACTIVO');
Insert into ADMI_CIUDAD values ('207','21','LAGO AGRIO','ACTIVO');
Insert into ADMI_CIUDAD values ('208','21','GONZALO PIZARRO','ACTIVO');
Insert into ADMI_CIUDAD values ('209','21','PUTUMAYO','ACTIVO');
Insert into ADMI_CIUDAD values ('210','21','SHUSHUFINDI','ACTIVO');
Insert into ADMI_CIUDAD values ('211','21','SUCUMBÍOS','ACTIVO');
Insert into ADMI_CIUDAD values ('212','21','CASCALES','ACTIVO');
Insert into ADMI_CIUDAD values ('213','21','CUYABENO','ACTIVO');
Insert into ADMI_CIUDAD values ('214','22','ORELLANA','ACTIVO');
Insert into ADMI_CIUDAD values ('215','22','AGUARICO','ACTIVO');
Insert into ADMI_CIUDAD values ('216','22','LA JOYA DE LOS SACHAS','ACTIVO');
Insert into ADMI_CIUDAD values ('217','22','LORETO','ACTIVO');
Insert into ADMI_CIUDAD values ('218','23','SANTO DOMINGO','ACTIVO');
Insert into ADMI_CIUDAD values ('219','24','SANTA ELENA','ACTIVO');
Insert into ADMI_CIUDAD values ('220','24','LA LIBERTAD','ACTIVO');
Insert into ADMI_CIUDAD values ('221','24','SALINAS','ACTIVO');
Insert into ADMI_CIUDAD values ('1','1','CUENCA','ACTIVO');
Insert into ADMI_CIUDAD values ('222','9','Samborondon','ELIMINADO');
Insert into ADMI_CIUDAD values ('242','7','PORTOVELO','ELIMINADO');
Insert into ADMI_CIUDAD values ('262','9','DURAN','ELIMINADO');
Insert into ADMI_CIUDAD values ('282','24','SALINAS','ACTIVO');
Insert into ADMI_CIUDAD values ('130','12','PALENQUE','ACTIVO');
Insert into ADMI_CIUDAD values ('115','11','PUYANGO','ACTIVO');
Insert into ADMI_CIUDAD values ('405','11','CALVAS','ACTIVO');
Insert into ADMI_CIUDAD values ('411','6','GUANO','ACTIVO');
Insert into ADMI_CIUDAD values ('417','13','MANGA DEL CURA','ACTIVO');
Insert into ADMI_CIUDAD values ('418','14','HUAMBOYA','ELIMINADO');
Insert into ADMI_CIUDAD values ('419','9','SAN JACINTO DE YAGUACHI','ACTIVO');
Insert into ADMI_CIUDAD values ('422','18','SAN PEDRO DE PELILEO','ELIMINADO');
Insert into ADMI_CIUDAD values ('506','18','BANOS DE AGUA SANTA','ELIMINADO');
Insert into ADMI_CIUDAD values ('409','15','CUYUJA','ELIMINADO');
Insert into ADMI_CIUDAD values ('404','11','CALVAS','ACTIVO');
Insert into ADMI_CIUDAD values ('406','10','TULCAN','ELIMINADO');
Insert into ADMI_CIUDAD values ('408','13','BOLIVAR','ACTIVO');
Insert into ADMI_CIUDAD values ('412','15','QUIJOS','ELIMINADO');
Insert into ADMI_CIUDAD values ('414','8','QUININDE','ACTIVO');
Insert into ADMI_CIUDAD values ('416','13','OLMEDO','ACTIVO');
Insert into ADMI_CIUDAD values ('73','8','RIOVERDE','ACTIVO');
Insert into ADMI_CIUDAD values ('66','7','LAS LAJAS','ACTIVO');
Insert into ADMI_CIUDAD values ('19','2','ECHEANDÍA','ACTIVO');
Insert into ADMI_CIUDAD values ('420','18','SAN PEDRO DE PELILEO1','ACTIVO');
Insert into ADMI_CIUDAD values ('421','18','PELILEO','ELIMINADO');
Insert into ADMI_CIUDAD values ('109','11','CELICA','ACTIVO');
Insert into ADMI_CIUDAD values ('85','9','NARANJAL','ACTIVO');
Insert into ADMI_CIUDAD values ('407','4','TULCAN','ELIMINADO');
Insert into ADMI_CIUDAD values ('410','15','QUIJOS','ELIMINADO');
Insert into ADMI_CIUDAD values ('413','13','BOLIVAR','ELIMINADO');
Insert into ADMI_CIUDAD values ('415','3','DELEG','ACTIVO');
Insert into ADMI_CIUDAD values ('68','8','ELOY ALFARO','ACTIVO');
Insert into ADMI_CIUDAD values ('77','9','BALAO','ACTIVO');
Insert into ADMI_CIUDAD values ('505','18','BANOS DE AGUA SANTA','ELIMINADO');
Insert into ADMI_CIUDAD values ('508','17','SAN MIGUEL DE URCUQUI','ACTIVO');
Insert into ADMI_CIUDAD values ('512','9','SIMON BOLIVAR','ACTIVO');
commit;