Insert into ADMI_PROVINCIA values ('2','BOLIVAR','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('3','CAÑAR','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('4','CARCHI','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('5','COTOPAXI','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('6','CHIMBORAZO','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('7','EL ORO','COSTA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('8','ESMERALDAS','COSTA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('9','GUAYAS','COSTA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('10','IMBABURA','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('11','LOJA','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('12','LOS RIOS','COSTA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('13','MANABI','COSTA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('14','MORONA SANTIAGO','ORIENTAL','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('15','NAPO','ORIENTAL','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('16','PASTAZA','ORIENTAL','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('17','PICHINCHA','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('18','TUNGURAHUA','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('19','ZAMORA CHINCHIPE','ORIENTAL','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('20','GALAPAGOS','INSULAR','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('21','SUCUMBIOS','ORIENTAL','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('22','ORELLANA','ORIENTAL','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('23','SANTO DOMINGO','SIERRA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('24','SANTA ELENA','COSTA','1','ACTIVO');
Insert into ADMI_PROVINCIA values ('1','AZUAY','SIERRA','1','ACTIVO');
commit;